CREATE DATABASE IF NOT EXISTS DB_BAR;

USE DB_BAR;

CREATE TABLE IF NOT EXISTS TB_LOGIN(
	ID_LOGIN INT AUTO_INCREMENT comment'Chave Primaria do Login',
    USU_LOGIN VARCHAR(30) UNIQUE NOT NULL comment'Usuario utilizado para o Login',
    SENHA_LOGIN VARCHAR(30)NOT NULL comment'Senha utilizado para o Login',
    PRIMARY KEY(ID_LOGIN) comment'Definindo chave Primaria'
) comment'Tabela de Login';

CREATE TABLE IF NOT EXISTS TB_FUNCIONARIO(
	ID_FUNCIONARIO INT AUTO_INCREMENT NOT NULL,
    NM_FUNCIONARIO VARCHAR(50) NOT NULL,
    TEL_FUNCIONARIO CHAR(10) NOT NULL,
    CEL_FUNCIONARIO CHAR(11) NOT NULL,
    RG_FUNCIONARIO CHAR(9) NOT NULL UNIQUE,
    CPF_FUNCIONARIO CHAR(11) NOT NULL UNIQUE,
    CIDADE_FUNCINARIO VARCHAR(40) NOT NULL,
    BAIRRO_FUNCIONARIO VARCHAR(40) NOT NULL,
    LOGRADOURO_FUNCIONARIO VARCHAR(70) NOT NULL,
    N_FUNCIONARIO VARCHAR(5) NOT NULL,
    COMPLEMENTO_FUNCIONARIO VARCHAR(40),
    IDENTIFICADOR_FUNCIONARIO CHAR(10) NOT NULL UNIQUE,
    BANCO_FUNCIONARIO VARCHAR(35) NOT NULL,
    CONTA_FUNCIONARIO VARCHAR(20) NOT NULL,
    AGENCIA_FUNCIONARIO VARCHAR(20) NOT NULL,
    PRIMARY KEY(ID_FUNCIONARIO)
) comment'Tabela de Funcionarios';

CREATE TABLE IF NOT EXISTS TB_PRODUTO(
	ID_PRODUTO INT AUTO_INCREMENT comment'Chave Primaria do Produto',
    NM_PRODUTO VARCHAR(45) NOT NULL comment'Nome do Produto',
    UM_PRODUTO VARCHAR(15) NOT NULL comment'Unida de Medida do Produto',
    QTD_PRODUTO INT NOT NULL comment'Quantidade de Produtos no estoque',
    VL_PRODUTO DOUBLE  NOT NULL comment'Valor do Produto',
    TP_PRODUTO VARCHAR(25) NOT NULL comment'Tipo do Produto',
    PRIMARY KEY(ID_PRODUTO)
) comment'Tabela de Produto';

/*ALTER TABLE TB_PRODUTO
CHANGE COLUMN PC_PRODUTO VL_PRODUTO DOUBLE NOT NULL;*/

INSERT INTO TB_LOGIN VALUES(DEFAULT,'ABC','123');

SELECT * FROM TB_Funcionario;

#DROP DATABASE DB_BAR;